services:
  db:
    image: postgres:16
    container_name: nexron-fitnesstracker-postgres
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-net

  adminer:
    image: adminer
    container_name: nexron-fitnesstracker-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - app-net

volumes:
  dbdata:

networks:
  app-net:
